language: c

sudo: required

env:
  matrix:
    # basic tests
    - TARGET=interp
    # haxe releases
    - TARGET=neko HAXE_VER=3.2.0
    - TARGET=neko HAXE_VER=3.1.3
    - TARGET=neko HAXE_VER=v3.1.0
    # haxe targets
    - TARGET=neko
    - TARGET=js TOOLCHAIN=default
    - TARGET=java
    - TARGET=cs
    - TARGET=cpp
    - TARGET=cpp ARCH=i686
    - TARGET=python
    - TARGET=php
    - TARGET=swf

matrix:
  fast_finish: true
  allow_failures:
    # - env: TARGET=neko HAXE_VER=v3.1.0
    - env: TARGET=cpp ARCH=i686

before_install:
  - travis_retry git clone --depth=50 --branch=master git://github.com/jonasmalacofilho/travis-hx.git ~/travis-hx

install:
  - ~/travis-hx/setup.sh
  - haxelib install utest

script:
  - cd $TRAVIS_BUILD_DIR
  # build the target. This will call haxe with the HXFLAGS and HXFLAGS_EXTRA environment variables
  - HXFLAGS="-main Test -cp test -cp lib -lib utest -D UNIT_TESTING_CSV -D travis" ~/travis-hx/build.sh
  # run the tests
  - ~/travis-hx/runtests.sh $FILENAME # this will set the $FILENAME defined on the environment variable to run the tests

